# Generated by Django 5.1.3 on 2024-12-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link',
            field=models.URLField(blank=True, help_text='Please specify payment link', max_length=500, null=True, verbose_name='Payment link'),
        ),
    ]
