# Generated by Django 5.1.3 on 2024-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe price ID', max_length=255, null=True, verbose_name='Stripe price ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe product ID', max_length=255, null=True, verbose_name='Stripe product ID'),
        ),
    ]
