# Generated by Django 5.1.3 on 2024-12-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_stripe_price_id_course_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount'),
        ),
    ]
